var wTypes = ['Sword',
  'Mace',
  'Long-sword',
  'Dagger',
  'Bow',
  'Brass knuckles',
  'Gauntlets',
  'Severed fist',
  'Plank, with a nail through it',
  'Club',
  'War pike',
  'Staff',
  'Whip',
  'Lance',
  'Axe',
  'War axe',
  'Sling',
  'Flamingo (animal)',
  'Flamingo (lawn ornament)',
  'Large trout',
  'Q-tip',
  'DSLR camera',
  'Bowling ball (thrown)',
  'Bowling ball (swung)',
  'Bottle of urine',
  'Insulting letter',
  'Rolled up newspaper',
  'Bong shaped like a coffee thermos',
  'POCKET SAND! SHA SHA SHAA!',
  'Lego caltrops',
  'Spoon',
  'Wooden spoon',
  'Fork',
  'Butterknife',
  'Stick of butter',
  'Squash',
  'Fly-swatter',
  'Lighter',
  'Nun-chucks',
  'Purple Binder',
  'Snowballs',
  'Wooden paddle',
  'Trident',
  'Kettle',
  'Pen',
  'Rapier',
  'Dry towel',
  'Wet towel',
  'Bastard sword',
  'Bass (fish)',
  'Katana',
  'Shovel (square)',
  'Shovel (spade)',
  'Scissors',
  'Bottle (wine)',
  'Bottle (water)',
  'Bottle (broken)',
  'Bottle (empty)',
  'Fireplace poker',
  'Love',
  'Mean look',
  'Rock (swung)',
  'Rock (thrown)',
  'Dab'
]
